name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_USERNAME: github-actions[bot]
          GITHUB_EMAIL: github-actions[bot]@users.noreply.github.com
          COMMIT_MESSAGE: 'Deploy to GitHub Pages'
        run: |
          git config --global user.name "$GITHUB_USERNAME"
          git config --global user.email "$GITHUB_EMAIL"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git reset --hard
          git clean -fd
          cp -r dist/* .
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push origin gh-pages --force
